import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  device: "",
};
export const layoutSlice = createSlice({
  name: "layout",
  initialState,
  reducers: {
    layoutChange: (state, action) => {
      const device =
        action.payload <= 576
          ? "mobile"
          : action.payload > 576 && action.payload <= 1024
          ? "tablet"
          : "desktop";
          state.device = device
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    // builder
    //   .addCase(incrementAsync.pending, (state) => {
    //     state.status = 'loading';
    //   })
    //   .addCase(incrementAsync.fulfilled, (state, action) => {
    //     state.status = 'idle';
    //     state.value += action.payload;
    //   });
  },
});

export const {layoutChange} = layoutSlice.actions;

export default layoutSlice.reducer;
